version: "3.0"
services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    ports:
      - 8097:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORTS=8097
      - UMASK=002
      - LIBTORRENT=v1
      - VPN_PIA_USER=${PIA_USERNAME}
      - VPN_PIA_PASS=${PIA_PASSWORD}
      - VPN_ENABLED=true 
      - VPN_CONF=wg0 
      - VPN_PROVIDER=pia 
      - VPN_LAN_NETWORK=192.168.1.0/24 
      - PRIVOXY_ENABLED=true
      - VPN_PIA_PREFERRED_REGION=Mexico
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - /mnt/media:/data
    restart: unless-stopped