version: "3.0"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Optional: Override the default umask (default is 022)
      - UMASK=022
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped