version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    container_name: gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USERNAME}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - VPN_TYPE=openvpn
      - SERVER_REGIONS=Mexico
      # REQUIRED: allow inbound ports through gluetun firewall
      - FIREWALL_VPN_INPUT_PORTS=6881,8097
      # optional but recommended
      - FIREWALL_INPUT_PORTS=8097
    ports:
      #All for Qbittorrent
      - 8097:8097
      - 6881:6881
      - 6881:6881/udp